### ISSUE TITLE
Make Nopipeline work with .Net Core on Linux

### ISSUE THREAD

**Issue by jamsilva** [Martenfur/Nopipeline#11]
I am unable to use Nopipeline as-is on Linux. However, changing all backslashes to slashes in Nopipeline.Task.targets makes things work correctly.
I expect macOS to have the same problem and I think Windows doesn't care but I only tested this change on Linux.

**Comment by Martenfur** [comment]
Macos actually works as is. If you'll confirm that it works on both linux and Windows, feel free to make a pr. I'll look into it later.

**Comment by Martenfur** [comment]
Merged your PR. ; -)
