### ISSUE TITLE
NoPipeline generating an odd structure for the MGCB file

### ISSUE THREAD

**Issue by jrasanen** [Martenfur/Nopipeline#18]
Hi!

I've been struggling to get the NoPipeline to work. Running nopipeline produces the MGCB but not the XNB files, and the MGCB file it outputs also has a very odd structure.

### Here's the content of the MGCB npl generates
<img width="410" alt="CleanShot 2022-12-04 at 16 13 51@2x" src="https://user-images.githubusercontent.com/13303/205495554-55d916e0-e626-467d-a126-dd0101dab076.png"> 

### Here's what the files look in the solution
<img width="328" alt="" src="https://user-images.githubusercontent.com/13303/205495614-041be8b1-b7d3-4ecc-ac95-870758c9426e.png">

[Here's the repository that reproduces the issue](https://github.com/jrasanen/content-pipeline-issue). I can reproduce this on macOS by running the NPL from the terminal or building the project with Visual Studio 2022 and the latest version of Rider.

### Nopipeline log is the following

I got this by running `dotnet "/Users/jussi/.nuget/packages/nopipeline.task/2.2.0/tools/net6.0/any/npl.dll" Jelly/Content/Content.npl`.

```
Nopipeline v2.2.0.0
Reading MGCB config /Users/jussi/tmp/ContentPipelineIssue/Jelly/Content/Content.mgcb

Reading setting: /outputDir:bin/$(Platform)
Reading setting: /intermediateDir:obj/$(Platform)
Reading setting: /config:
Reading setting: /profile:Reach
Reading setting: /compress:False

Reading content:././Graphics/fire.png
Reading content:././Graphics/jelly.png
Reading content:./Graphics/jelly.png
Reading content:./Graphics/fire.png
Reading content:Graphics/jelly.png
Reading content:Graphics/fire.png
Finished reading MGCB config! Got 6 items.

-------------------------------------

Reading NPL config.

No root found! Using default paths.



Reading content for: Graphics/*.png
    Reading Graphics/fire.png
    Reading Graphics/jelly.png

Finished reading NPL config!

-------------------------------------

Checking integrity of the final config.

Checking /Users/jussi/tmp/ContentPipelineIssue/Jelly/Content/././Graphics/fire.png
Checking /Users/jussi/tmp/ContentPipelineIssue/Jelly/Content/././Graphics/jelly.png
Checking /Users/jussi/tmp/ContentPipelineIssue/Jelly/Content/./Graphics/jelly.png
Checking /Users/jussi/tmp/ContentPipelineIssue/Jelly/Content/./Graphics/fire.png
Checking /Users/jussi/tmp/ContentPipelineIssue/Jelly/Content/Graphics/jelly.png
Checking /Users/jussi/tmp/ContentPipelineIssue/Jelly/Content/Graphics/fire.png

Updating snapshot!


-------------------------------------

Saving new config as /Users/jussi/tmp/ContentPipelineIssue/Jelly/Content/Content.mgcb

DONE. o-o
```

Any pointers for getting this work are appreciated. Hopefully, I'm just doing something obvious very wrong.

**Comment by Martenfur** [comment]
Ok, first of all, your project is weird as hell. It couldn't even launch because global.json had net7 specified, but the csproj had net6. Lang version was set to 11 which net6 is not. Fixed all those issues, built the project on windows, this is what I got:

```
#----------------------------- Global Properties ----------------------------#

/outputDir:bin/$(Platform)
/intermediateDir:obj/$(Platform)
/config:
/profile:Reach
/compress:False

#-------------------------------- References --------------------------------#


#---------------------------------- Content ---------------------------------#

#begin Graphics/fire.png
/importer:TextureImporter
/processor:TextureProcessor
/processorParam:ColorKeyColor=255,0,255,255
/processorParam:ColorKeyEnabled=True
/processorParam:GenerateMipmaps=False
/processorParam:PremultiplyAlpha=True
/processorParam:ResizeToPowerOfTwo=False
/processorParam:MakeSquare=False
/processorParam:TextureFormat=Color
/build:Graphics/fire.png

#begin Graphics/jelly.png
/importer:TextureImporter
/processor:TextureProcessor
/processorParam:ColorKeyColor=255,0,255,255
/processorParam:ColorKeyEnabled=True
/processorParam:GenerateMipmaps=False
/processorParam:PremultiplyAlpha=True
/processorParam:ResizeToPowerOfTwo=False
/processorParam:MakeSquare=False
/processorParam:TextureFormat=Color
/build:Graphics/jelly.png
```

Looks like macos shenanigans to me, or the fucked up project. Check if the files exist at those weird paths - note that the folders are hidden since their names begin with a dot.

Your logs also show that NPL only finds two files at the correct paths and pulls dotted versions from an existing mgcb config - so delete the mgcb file and try again.

**Comment by jrasanen** [comment]
Thank you for your response and insights!

> Ok, first of all, your project is weird as hell. It couldn't even launch because global.json had net7 specified, but the csproj had net6. Lang version was set to 11 which net6 is not. Fixed all those issues, built the project on windows

Good that you found at least a part of the issue to be the project’s structure. Fixing those will most likely fix the problem on macOS as well.

> Check if the files exist at those weird paths - note that the folders are hidden since their names begin with a dot.

Yes, those files don’t exist on the file system and would be hidden if they did.

> Your logs also show that NPL only finds two files at the correct paths and pulls dotted versions from an existing mgcb config - so delete the mgcb file and try again.

The reproduction repository doesn’t have an existing MGCB file, only the one generated by the NPL, hence this issue.

Thank you for taking the time to assess that the problem most likely is the project’s structure.

**Comment by jrasanen** [comment]
After making the proposed project template fixes, it generates the files successfully without the odd structure, so closing the issue.
