### ISSUE TITLE
Unix paths don't work as expected

### ISSUE THREAD

**Issue by greenstack** [Martenfur/Nopipeline#19]
When putting in a Unix path to the references block in the .npl, the paths don't resolve as expected. For example, `~/.nuget/packages/...` resolves to `{Project Working Directory}/~/.nuget/packages/...`. The expected behavior would be for it to resolve to `{home directory}/~/.nuget/packages/...`. Likewise, `/etc/...` resolves to `{Project Working Directory}/etc/...` instead of `/etc/...`.

A workaround solution could be platform-specific reference settings in the .npl file.

**Comment by Martenfur** [comment]
I really don't recommend doing that. Paths should be relative. The fix would be hard to implement, as I don't use Linux, and would promote a bad practice. Use relative paths instead.
