### ISSUE TITLE
Error importing Xml

### ISSUE THREAD

**Issue by dvinerlove** [Martenfur/Nopipeline#23]
Content.npl

"styles":
		{
			"path": "Styles/*.xml",
			"recursive": "True",
			"action": "build",
			"importer": "XmlImporter",
			"processor": "PassThroughProcessor",
		}

when build
The command "dotnet mgcb /quiet /@:"Z:\RPS\RPS.GL\Content\Content.mgcb" /platform:DesktopGL /outputDir:"Z:/RPS/RPS.GL/Content/bin/DesktopGL/Content" /intermediateDir:"Z:/RPS/RPS.GL/Content/obj/DesktopGL/net8.0/Content" /workingDir:"Z:/RPS/RPS.GL/Content/"” exited with code 1.

**Comment by Martenfur** [comment]
That not a Nopipeline issue, that's a mgcb issue.
