### ISSUE TITLE
Does this work on macOS?

### ISSUE THREAD

**Issue by BE-Code** [Martenfur/Nopipeline#24]
I am working from a mac with an m2 chip. I want to use nopipeline because I can't get mgcb editor working. I've tried everything I could find as far as using the x64 version of dotnet.
I installed nuget and ran `nuget install Nopipeline.Task`. That added a folder to my project. I'm not sure how to proceed to get the default configuration file for nopipeline. Running `dotnet run` doesn't seem to do it. How can I get this working?

**Comment by Martenfur** [comment]
All Nopipeline does is generate an mgcb config for the regular pipeline tool. It's not tied to any platform, should work fine. But your mbcb should be able to successfully compile. Read the readme for setup.
