### ISSUE TITLE
Possible to install as NuGet package?

### ISSUE THREAD

**Issue by jonathanpmast** [Martenfur/Nopipeline#3]
Rather than have this be deployed via an exe/vsix, would it be possible to deploy this as a nuget package, similar to how the Monogame.Content.Builder nuget works?

I believe the package would just need an exe/dll and a targets file, very similar to how the [monogame nuget files work](https://github.com/MonoGame/MonoGame/blob/develop/NuGetPackages/MonoGame.Framework.DesktopGL.nuspec)

Curious if this has been explored at all?  If not, maybe I'll take a shot at submitting a PR.  

This seems to me like it would be a much simpler integration/installation story...

**Comment by Martenfur** [comment]
I've looked into that briefly. The main issue is that nuget needs to install .targets entry into .csproj BEFORE Pipeline tool's entry. Otherwise Nopipeline will not work properly. If you'll be able to somehow do it -- go ahead.

**Comment by Martenfur** [comment]
@jonathanpmast Just released v1.1. If you're gonna do anything, update your fork, I've changed pretty much the whole codebase.

**Comment by persn** [comment]
> I've looked into that briefly. The main issue is that nuget needs to install .targets entry into .csproj BEFORE Pipeline tool's entry. Otherwise Nopipeline will not work properly. If you'll be able to somehow do it -- go ahead.

Is it possible to use a .props file instead? .props files are imported before .target files https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#choose-between-adding-properties-to-a-props-or-targets-file

**Comment by Martenfur** [comment]
@persn You can certainly try. : - )

**Comment by Martenfur** [comment]
Now Nopipeline is distributed entirely via nuget. It's not available right now, but will be in a couple of days.
