### ISSUE TITLE
Linked files (mgcb)

### ISSUE THREAD

**Issue by KakCAT** [Martenfur/Nopipeline#5]
Are there plans to support linked files? I usually have my code (and content.mgcb file) in a development drive and all my assets are in another drive, which forces me to use 'linking' in my MGCB for all my files.

https://github.com/MonoGame/MonoGame/issues/5109

Thanks!

**Comment by KakCAT** [comment]
Hi!

I decided to go ahead and implement the feature myself as I'm a bit in a hurry.

As I only use linked files I may have broken something in the 'normal' path (honestly I haven't tested it) but I leave it here just in case somebody is interested in it as a base for a better solution:

https://github.com/KakCAT/NoPipeline/commit/78c05c6acadc45675d27c3a4c940c5ce51052798

There's one big problem though, if possible, the content pipeline program converts the rooted path into relative paths (i.e. ../../../rootFolder/blabla) if you open the mgcb file, so if you combine generating the mgcb file and editing with the content pipeline program duplicate file inclusions will happen

**Comment by Martenfur** [comment]
Sure, go ahead, I've never used linked resources myself. Just follow the codestyle. =]

**Comment by Martenfur** [comment]
Added full linking support. Check out the new sample project to see how it works.
