### ISSUE TITLE
.Net Core

### ISSUE THREAD

**Issue by OAguinagalde** [Martenfur/Nopipeline#7]
Hello,
Just in case anyone is interested, I made it compatible in .net Core (3.1). Also deleted some things on the process tho, like the sample application which I couldn't compile as it requires some things from other packages that I don't have (And also didn't care about those). It's [here] (https://github.com/OAguinagalde/NoPipeline).

@Martenfur feel free to update your repo if necessary.

**Comment by OAguinagalde** [comment]
Also, I'm using NoPipeline as a command line tool, which as far as I know it's not the way it's supposed to be used (The Readme states something about how to make it work by putting some stuff in the csproj file?). It might be something else that would work, I don't know as I don't use it that way.

**Comment by Martenfur** [comment]
Sure, create a pull request -- I'll look into it. But bring back "useless" stuff like .targets files and sample. You've broke half the functionality and purged the sample. : D

**Comment by Martenfur** [comment]
> I know it's not the way it's supposed to be used
This is absolutely not the way to use it. You should integrate it into your project as the guide in readme says. This way Nopipeline will trigger automatically on each build.

I was thinking about making it a nuget, tho.

**Comment by Martenfur** [comment]
Ported Nopipeline over to netcore and made it a dotnet tool, so now it should support all platforms.

**Comment by OAguinagalde** [comment]
Thanks for the update! Specially the dotnet tool 😄
