### ISSUE TITLE
Full paths instead of Relative paths not working as expected

### ISSUE THREAD

**Issue by OAguinagalde** [Martenfur/Nopipeline#8]
Hello @Martenfur 
I'm not 100% positive, but I couldn't make it work with full paths instead of relative paths. I was getting paths like `C:\Path\To\ContentC:\Path\To\Project\Content` and things like that. I ended up fixing it, at least for my specific use case. I would issue a Pull Request but in my fork I also got rid of some things and updated it to be compatible with .Net Core so if you want to check it out, the changes I made and an explanation are in [my fork (b9aac72)](https://github.com/OAguinagalde/NoPipeline/commit/b9aac72dee7d60cee9ec248249f3d52d2742bc52). The changes are a couple of lines but let me know if there is a better way of fixing the isse. For all I know I fixed my case but made it not work with plenty of other cases, didn't really test it in depth.

Cheers.

**Comment by Martenfur** [comment]
Probably fixed now.

**Comment by OAguinagalde** [comment]
Can confirm, thanks! 👍
